package HRComponents.GlobalProjectPattern.DevKit;
import HRComponents.AbstractionImp.CRUDImpService.CRUDImpServiceJoinsEntitys.UsersJoinSystemUsersMethod;
import HRComponents.AbstractionImp.CRUDImpService.CRUDImpServiceSingleEntity.CRUDUsersServiceMethod;
public abstract  class DevFactory{
protected abstract CRUDUsersServiceMethod crudUsersServiceMethod();
protected  abstract UsersJoinSystemUsersMethod usersJoinSystemUsersMethod();

}
